apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 3  # Number of replicas (pods) of your application
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: localhost:5000/user:latest  # Replace with your image name
        ports:
        - containerPort: 9002  # Replace with your application port