apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 9002  # External port for accessing your application (can be different from container port)
      targetPort: 9002  # Port your application listens on within the container
  type: LoadBalancer  # Choose a service type based on your needs (e.g., LoadBalancer for external access)